# Desafio

A empresa Você Mais Seguro fornece planos de saúde e seguros de vida. 
A empresa está interessada em lança um novo seguro de veiculos, e desja entender a propensão de compra de seus clientes para este novo cenário. 
Em uma primeira etapa, foi realizada uma grande pesquisa com seus cleintes, para entender quais destes clientes estariam interessados em adquirir o novo seguro de veiculos.

Agora, com novos clientes do plano de saude entrando para sua base, a empresa deseja entender quais destes novos clientes teriam maior propensão de compra do novo seguro de veiculos.
No entanto, a empresa não esta interessada em gastar com pesquisas para todos os novos clientes, e sim apenas para aqueles que tem maior propensão de compra, 
haja visto,que seu efetivo comercial, não é capaz de entrar em contato, para fornecer um processo de pré vendas personalizado para toda a base de seus novos clientes, somente
para 2000 deles de cada vez. 

Para isso, este projeto tem como objetivo apresentar uma lista, com os 2000 clientes com maior probabilidade de venda do seguro de veículos.

# 0.0 Imports

In [1]:
import pandas as pd 
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

### 0.1 Helper Functions

In [ ]:
def jupyter_settings():
    %matplotlib inline
    %pylab inline

    plt.style.use( 'bmh' )
    plt.rcParams['figure.figsize'] = [25, 8]
    plt.rcParams['font.size'] = 24
    pd.options.display.max_columns = None
    pd.options.display.max_rows = None
    pd.set_option( 'display.expand_frame_repr', False )
    sns.set()

jupyter_settings()

def print_descriptive_stats(df,
                            column):
    print(f'**Clientes que adquiririam o Seguro - {column} statistics**')
    print(df[df.Response == 1][column].describe())
    print('-'*45)
    print(f'**Clientes NAO que adquiririam o Seguro - {column} statistics**')
    print(df[df.Response == 0][column].describe())
    print('\n')

def get_frequency_table(df, column): 

    df_frequency_1 = df[df.Response == 1].groupby(column).Response.count().reset_index()
    df_frequency_1.rename(columns={'Response':'Count_Response_1'}, inplace=True)


    df_frequency_0 = df[df.Response == 0].groupby(column).Response.count().reset_index()
    df_frequency_0.rename(columns={'Response':'Count_Response_0'}, inplace=True)

    df_frequency = pd.merge(df_frequency_1, df_frequency_0, on=column, how='inner') 
    df_frequency['Total'] = df_frequency['Count_Response_1'] + df_frequency['Count_Response_0']
    df_frequency['Propensity_to_buy'] = df_frequency['Count_Response_1']/df_frequency['Total']
    df_frequency['%_sample_to_buy'] = df_frequency['Count_Response_1']/df_frequency['Count_Response_1'].sum() 
    df_frequency['%_sample_to_not_buy'] = df_frequency['Count_Response_0']/df_frequency['Count_Response_0'].sum() 
    df_frequency['%_sample_size']   = df_frequency['Total']/len(df)
    df_frequency['%_general_propensity_to_buy'] = len(df[df.Response==1])/len(df)
    
    return df_frequency


def transform_pipeline(df):

    '''
    [EM FASE DE VALIDACAO....]
    '''
    from sklearn.preprocessing import StandardScaler, MinMaxScaler 


    region_code = df.Region_Code.copy()
    dummies_region_code = pd.get_dummies(region_code,prefix = "region_code")

    sales_channel = df.Policy_Sales_Channel.copy()
    dummies_sales_channel = pd.get_dummies(sales_channel,prefix = "policy_sales_channel")

    df_copy = df.copy()
    df_encoded = pd.concat([df_copy, dummies_sales_channel, dummies_region_code], axis = 1)


    df_encoded.drop(columns = ['Region_Code','Policy_Sales_Channel'], inplace = True)

    map_sexo_feminino = {
        'Male' : 0,
        'Female' : 1 
    }

    df_encoded['sexo_feminino'] = df_encoded.Gender.map(map_sexo_feminino)


    df_encoded.Vehicle_Damage = df_encoded.Vehicle_Damage.map({
        'Yes' : 1,
        'No'  : 0
    })


    scaller_premium      = MinMaxScaler()
    scaller_vintage      = MinMaxScaler()
    scaller_age          = MinMaxScaler()
    scaller_faixa_etaria = MinMaxScaler()

    df_encoded.Vintage_Scalled        = scaller_vintage.fit_transform(df_encoded.Vintage.values.reshape(-1,1))
    df_encoded.Annual_Premium_Scalled = scaller_premium.fit_transform(df_encoded.Annual_Premium.values.reshape(-1,1))


    df_encoded.Age        = scaller_age.fit_transform(df_encoded.Age.values.reshape(-1,1))
    df_encoded.faixa_etaria        = scaller_faixa_etaria.fit_transform(df_encoded.faixa_etaria.values.reshape(-1,1))


    df_encoded.Annual_Premium.describe()

    df_to_model = df_encoded[[x for x in df_encoded.columns if x not in ['id','Vintage_months','Vintage_weeks','Vintage']]]
    df_to_model.columns
    return df_to_model

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

# 1.0 Limpeza dos Dados

**Tipos de limpezas**

* Nulos
* Tipagem inconsistente 
* Claros outliers (indicio de erro de digitação)

### 1.1 - Conhecendo o Dataset

In [3]:
df_raw = pd.read_csv('../data/raw/data.csv')
df_raw.head()

   id  Gender  Age  Driving_License  Region_Code  Previously_Insured Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  Response
0   1    Male   44                1         28.0                   0   > 2 Years            Yes         40454.0                  26.0      217         1
1   2    Male   76                1          3.0                   0    1-2 Year             No         33536.0                  26.0      183         0
2   3    Male   47                1         28.0                   0   > 2 Years            Yes         38294.0                  26.0       27         1
3   4    Male   21                1         11.0                   1    < 1 Year             No         28619.0                 152.0      203         0
4   5  Female   29                1         41.0                   1    < 1 Year             No         27496.0                 152.0       39         0

# 3.0 - Preparação dos dados

In [ ]:
df_3 = df_raw.copy()
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243909 entries, 217927 to 169494
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    243909 non-null  int64
 1   Gender                243909 non-null  object
 2   Age                   243909 non-null  int64
 3   Driving_License       243909 non-null  int64
 4   Region_Code           243909 non-null  float64
 5   Previously_Insured    243909 non-null  int64
 6   Vehicle_Age           243909 non-null  object
 7   Vehicle_Damage        243909 non-null  object
 8   Annual_Premium        243909 non-null  float64
 9   Policy_Sales_Channel  243909 non-null  float64
 10  Vintage               243909 non-null  int64
 11  Response              243909 non-null  int64
 12  Vintage_months        243909 non-null  int64
 13  Vintage_weeks         243909 non-null  int64
 14  faixa_etaria          243909 non-null  int64
dtypes: float64(3), int64(9), object(3)
memory usage: 29.8+ MB

### 3.1 - Encodings

#### 3.1.1 - One Hot Encoding (dummi)

* Policy Sales Channel 
* Region Code

**Region Code**

A justificativa se da pela ausencia de elação quantitativa nos dados de region code. 

A regiao "102" ser maior que a regiao "32" não faz sentido

In [49]:
region_code = df_3.Region_Code.copy()
dummies_region_code = pd.get_dummies(region_code,prefix = "region_code")
dummies_region_code.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243909 entries, 217927 to 169494
Data columns (total 53 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   region_code_0.0   243909 non-null  bool
 1   region_code_1.0   243909 non-null  bool
 2   region_code_2.0   243909 non-null  bool
 3   region_code_3.0   243909 non-null  bool
 4   region_code_4.0   243909 non-null  bool
 5   region_code_5.0   243909 non-null  bool
 6   region_code_6.0   243909 non-null  bool
 7   region_code_7.0   243909 non-null  bool
 8   region_code_8.0   243909 non-null  bool
 9   region_code_9.0   243909 non-null  bool
 10  region_code_10.0  243909 non-null  bool
 11  region_code_11.0  243909 non-null  bool
 12  region_code_12.0  243909 non-null  bool
 13  region_code_13.0  243909 non-null  bool
 14  region_code_14.0  243909 non-null  bool
 15  region_code_15.0  243909 non-null  bool
 16  region_code_16.0  243909 non-null  bool
 17  region_code_17.0  243909 non-null  bool
 18  region_code_18.0  243909 non-null  bool
 19  region_code_19.0  243909 non-null  bool
 20  region_code_20.0  243909 non-null  bool
 21  region_code_21.0  243909 non-null  bool
 22  region_code_22.0  243909 non-null  bool
 23  region_code_23.0  243909 non-null  bool
 24  region_code_24.0  243909 non-null  bool
 25  region_code_25.0  243909 non-null  bool
 26  region_code_26.0  243909 non-null  bool
 27  region_code_27.0  243909 non-null  bool
 28  region_code_28.0  243909 non-null  bool
 29  region_code_29.0  243909 non-null  bool
 30  region_code_30.0  243909 non-null  bool
 31  region_code_31.0  243909 non-null  bool
 32  region_code_32.0  243909 non-null  bool
 33  region_code_33.0  243909 non-null  bool
 34  region_code_34.0  243909 non-null  bool
 35  region_code_35.0  243909 non-null  bool
 36  region_code_36.0  243909 non-null  bool
 37  region_code_37.0  243909 non-null  bool
 38  region_code_38.0  243909 non-null  bool
 39  region_code_39.0  243909 non-null  bool
 40  region_code_40.0  243909 non-null  bool
 41  region_code_41.0  243909 non-null  bool
 42  region_code_42.0  243909 non-null  bool
 43  region_code_43.0  243909 non-null  bool
 44  region_code_44.0  243909 non-null  bool
 45  region_code_45.0  243909 non-null  bool
 46  region_code_46.0  243909 non-null  bool
 47  region_code_47.0  243909 non-null  bool
 48  region_code_48.0  243909 non-null  bool
 49  region_code_49.0  243909 non-null  bool
 50  region_code_50.0  243909 non-null  bool
 51  region_code_51.0  243909 non-null  bool
 52  region_code_52.0  243909 non-null  bool
dtypes: bool(53)
memory usage: 14.2 MB

**Policy Sales Channel**

In [ ]:

sales_channel = df_3.Policy_Sales_Channel.copy()
dummies_sales_channel = pd.get_dummies(sales_channel,prefix = "policy_sales_channel")
dummies_sales_channel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243909 entries, 217927 to 169494
Columns: 148 entries, policy_sales_channel_1.0 to policy_sales_channel_163.0
dtypes: bool(148)
memory usage: 36.3 MB

In [51]:
dummies_sales_channel.head(5)

        policy_sales_channel_1.0  policy_sales_channel_2.0  policy_sales_channel_3.0  policy_sales_channel_4.0  policy_sales_channel_6.0  policy_sales_channel_7.0  policy_sales_channel_8.0  policy_sales_channel_9.0  policy_sales_channel_10.0  policy_sales_channel_11.0  policy_sales_channel_12.0  policy_sales_channel_13.0  policy_sales_channel_14.0  policy_sales_channel_15.0  policy_sales_channel_16.0  policy_sales_channel_17.0  policy_sales_channel_18.0  policy_sales_channel_19.0  policy_sales_channel_20.0  policy_sales_channel_21.0  policy_sales_channel_22.0  policy_sales_channel_23.0  policy_sales_channel_24.0  policy_sales_channel_25.0  policy_sales_channel_26.0  policy_sales_channel_27.0  policy_sales_channel_29.0  policy_sales_channel_30.0  policy_sales_channel_31.0  policy_sales_channel_32.0  policy_sales_channel_33.0  policy_sales_channel_34.0  policy_sales_channel_35.0  policy_sales_channel_36.0  policy_sales_channel_37.0  policy_sales_channel_38.0  policy_sales_channel_39.0  policy_sales_channel_40.0  policy_sales_channel_42.0  policy_sales_channel_43.0  policy_sales_channel_44.0  policy_sales_channel_45.0  policy_sales_channel_46.0  policy_sales_channel_47.0  policy_sales_channel_48.0  policy_sales_channel_49.0  policy_sales_channel_50.0  policy_sales_channel_51.0  policy_sales_channel_52.0  policy_sales_channel_53.0  policy_sales_channel_54.0  policy_sales_channel_55.0  policy_sales_channel_56.0  policy_sales_channel_57.0  policy_sales_channel_58.0  policy_sales_channel_59.0  policy_sales_channel_60.0  policy_sales_channel_61.0  policy_sales_channel_62.0  policy_sales_channel_63.0  policy_sales_channel_64.0  policy_sales_channel_65.0  policy_sales_channel_66.0  policy_sales_channel_67.0  policy_sales_channel_68.0  policy_sales_channel_69.0  policy_sales_channel_70.0  policy_sales_channel_71.0  policy_sales_channel_73.0  policy_sales_channel_76.0  policy_sales_channel_78.0  policy_sales_channel_79.0  policy_sales_channel_80.0  policy_sales_channel_81.0  policy_sales_channel_82.0  policy_sales_channel_83.0  policy_sales_channel_86.0  policy_sales_channel_87.0  policy_sales_channel_88.0  policy_sales_channel_89.0  policy_sales_channel_90.0  policy_sales_channel_91.0  policy_sales_channel_92.0  policy_sales_channel_93.0  policy_sales_channel_94.0  policy_sales_channel_95.0  policy_sales_channel_96.0  policy_sales_channel_97.0  policy_sales_channel_98.0  policy_sales_channel_99.0  policy_sales_channel_100.0  policy_sales_channel_101.0  policy_sales_channel_102.0  policy_sales_channel_103.0  policy_sales_channel_104.0  policy_sales_channel_105.0  policy_sales_channel_106.0  policy_sales_channel_107.0  policy_sales_channel_108.0  policy_sales_channel_109.0  policy_sales_channel_110.0  policy_sales_channel_111.0  policy_sales_channel_112.0  policy_sales_channel_113.0  policy_sales_channel_114.0  policy_sales_channel_115.0  policy_sales_channel_116.0  policy_sales_channel_117.0  policy_sales_channel_118.0  policy_sales_channel_119.0  policy_sales_channel_120.0  policy_sales_channel_121.0  policy_sales_channel_122.0  policy_sales_channel_123.0  policy_sales_channel_124.0  policy_sales_channel_125.0  policy_sales_channel_126.0  policy_sales_channel_127.0  policy_sales_channel_128.0  policy_sales_channel_129.0  policy_sales_channel_130.0  policy_sales_channel_131.0  policy_sales_channel_132.0  policy_sales_channel_133.0  policy_sales_channel_134.0  policy_sales_channel_135.0  policy_sales_channel_136.0  policy_sales_channel_137.0  policy_sales_channel_138.0  policy_sales_channel_139.0  policy_sales_channel_140.0  policy_sales_channel_144.0  policy_sales_channel_145.0  policy_sales_channel_146.0  policy_sales_channel_147.0  policy_sales_channel_148.0  policy_sales_channel_150.0  policy_sales_channel_151.0  policy_sales_channel_152.0  policy_sales_channel_153.0  policy_sales_channel_154.0  policy_sales_channel_155.0  policy_sales_channel_156.0  policy_sales_channel_157.0  policy_sales_channel_158.0  policy_sales_channel_159.0  policy_sales_channel_160.0  policy_sales_channel_163.0
217927                     False                     False                     False                     False                     False                     False                     False                     False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                        True                       False                       False                       False                       False                       False                       False                       False                       False                       False
54207                      False                     False                     False                     False                     False                     False                     False                     False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                        True                       False
18364                      False                     False                     False                     False                     False                     False                     False                     False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                        True                       False                       False                       False                       False                       False                       False                       False

**Merge ao dataset original**

In [ ]:
df_3_copy = df_3.copy()
df_3_encoded = pd.concat([df_3_copy, dummies_sales_channel, dummies_region_code], axis = 1)


df_3_encoded.drop(columns = ['Region_Code','Policy_Sales_Channel'], inplace = True)
df_3_encoded.shape

(243909, 214)

**Region Code**

#### 3.1.2 - Binary Encoding

* Gender
* Driving License
* Previously Insured
* Vehicle Damage
* Response

In [53]:
df_3_encoded.Gender.value_counts()

Gender
Male      131704
Female    112205
Name: count, dtype: int64

In [ ]:

map_sexo_feminino = {
    'Male' : 0,
    'Female' : 1 
}

df_3_encoded['sexo_feminino'] = df_3_encoded.Gender.map(map_sexo_feminino)

**Checagem dos demais campos**

In [55]:
df_3_encoded.Driving_License.value_counts()

Driving_License
1    243373
0       536
Name: count, dtype: int64

In [56]:
df_3_encoded.Previously_Insured.value_counts()

Previously_Insured
0    132145
1    111764
Name: count, dtype: int64

In [57]:
df_3_encoded.Vehicle_Damage.value_counts()

Vehicle_Damage
Yes    123248
No     120661
Name: count, dtype: int64

In [ ]:
df_3_encoded.Vehicle_Damage = df_3_encoded.Vehicle_Damage.map({
    'Yes' : 1,
    'No'  : 0
})

df_3_encoded.Vehicle_Damage.value_counts()

Vehicle_Damage
1    123248
0    120661
Name: count, dtype: int64

In [59]:
df_3_encoded.Response.value_counts()

Response
0    214210
1     29699
Name: count, dtype: int64

## 3.2 - Variaveis Numéricas (Padronização,  Normalização, transformação ciclica, etc.)

In [ ]:


df_3_encoded[[x for x in df_3_encoded.columns if '.0' not in x]].info()

<class 'pandas.core.frame.DataFrame'>
Index: 243909 entries, 217927 to 169494
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  243909 non-null  int64
 1   Gender              243909 non-null  object
 2   Age                 243909 non-null  int64
 3   Driving_License     243909 non-null  int64
 4   Previously_Insured  243909 non-null  int64
 5   Vehicle_Age         243909 non-null  object
 6   Vehicle_Damage      243909 non-null  int64
 7   Annual_Premium      243909 non-null  float64
 8   Vintage             243909 non-null  int64
 9   Response            243909 non-null  int64
 10  Vintage_months      243909 non-null  int64
 11  Vintage_weeks       243909 non-null  int64
 12  faixa_etaria        243909 non-null  int64
 13  sexo_feminino       243909 non-null  int64
dtypes: float64(1), int64(11), object(2)
memory usage: 27.9+ MB

In [61]:
df_3_encoded.Vintage.values.shape

(243909,)

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler 


scaller_premium      = MinMaxScaler()
scaller_vintage      = MinMaxScaler()
scaller_age          = MinMaxScaler()
scaller_faixa_etaria = MinMaxScaler()

df_3_encoded.Vintage_Scalled        = scaller_vintage.fit_transform(df_3_encoded.Vintage.values.reshape(-1,1))
df_3_encoded.Annual_Premium_Scalled = scaller_premium.fit_transform(df_3_encoded.Annual_Premium.values.reshape(-1,1))


df_3_encoded.Age        = scaller_age.fit_transform(df_3_encoded.Age.values.reshape(-1,1))
df_3_encoded.faixa_etaria        = scaller_faixa_etaria.fit_transform(df_3_encoded.faixa_etaria.values.reshape(-1,1))


df_3_encoded.Annual_Premium.describe()

/tmp/ipykernel_244565/4176306129.py:8: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_3_encoded.Vintage_Scalled        = scaller_vintage.fit_transform(df_3_encoded.Vintage.values.reshape(-1,1))
/tmp/ipykernel_244565/4176306129.py:9: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_3_encoded.Annual_Premium_Scalled = scaller_premium.fit_transform(df_3_encoded.Annual_Premium.values.reshape(-1,1))

count    243909.000000
mean      30551.996982
std       17223.027159
min        2630.000000
25%       24394.000000
50%       31671.000000
75%       39398.000000
max      540165.000000
Name: Annual_Premium, dtype: float64

In [ ]:
df_to_model = df_3_encoded[[x for x in df_3_encoded.columns if x not in ['id','Vintage_months','Vintage_weeks','Vintage']]]
df_to_model.columns

Index(['Gender', 'Age', 'Driving_License', 'Previously_Insured', 'Vehicle_Age',
       'Vehicle_Damage', 'Annual_Premium', 'Response', 'faixa_etaria',
       'policy_sales_channel_1.0',
       ...
       'region_code_44.0', 'region_code_45.0', 'region_code_46.0',
       'region_code_47.0', 'region_code_48.0', 'region_code_49.0',
       'region_code_50.0', 'region_code_51.0', 'region_code_52.0',
       'sexo_feminino'],
      dtype='object', length=211)

### 3.3 - Seleção de variaveis

In [ ]:
def transform_pipeline(df_1):

    '''
    [EM FASE DE VALIDACAO....]
    '''
    from sklearn.preprocessing import StandardScaler, MinMaxScaler 


    region_code = df_3.Region_Code.copy()
    dummies_region_code = pd.get_dummies(region_code,prefix = "region_code")

    sales_channel = df_3.Policy_Sales_Channel.copy()
    dummies_sales_channel = pd.get_dummies(sales_channel,prefix = "policy_sales_channel")

    df_3_copy = df_3.copy()
    df_3_encoded = pd.concat([df_3_copy, dummies_sales_channel, dummies_region_code], axis = 1)


    df_3_encoded.drop(columns = ['Region_Code','Policy_Sales_Channel'], inplace = True)

    map_sexo_feminino = {
        'Male' : 0,
        'Female' : 1 
    }

    df_3_encoded['sexo_feminino'] = df_3_encoded.Gender.map(map_sexo_feminino)


    df_3_encoded.Vehicle_Damage = df_3_encoded.Vehicle_Damage.map({
        'Yes' : 1,
        'No'  : 0
    })


    scaller_premium      = MinMaxScaler()
    scaller_vintage      = MinMaxScaler()
    scaller_age          = MinMaxScaler()
    scaller_faixa_etaria = MinMaxScaler()

    df_3_encoded.Vintage_Scalled        = scaller_vintage.fit_transform(df_3_encoded.Vintage.values.reshape(-1,1))
    df_3_encoded.Annual_Premium_Scalled = scaller_premium.fit_transform(df_3_encoded.Annual_Premium.values.reshape(-1,1))


    df_3_encoded.Age        = scaller_age.fit_transform(df_3_encoded.Age.values.reshape(-1,1))
    df_3_encoded.faixa_etaria        = scaller_faixa_etaria.fit_transform(df_3_encoded.faixa_etaria.values.reshape(-1,1))


    df_3_encoded.Annual_Premium.describe()

    df_to_model = df_3_encoded[[x for x in df_3_encoded.columns if x not in ['id','Vintage_months','Vintage_weeks','Vintage']]]
    df_to_model.columns
    return df_to_model

Index(['Gender', 'Age', 'Driving_License', 'Previously_Insured', 'Vehicle_Age',
       'Vehicle_Damage', 'Annual_Premium', 'Response', 'faixa_etaria',
       'policy_sales_channel_1.0',
       ...
       'region_code_44.0', 'region_code_45.0', 'region_code_46.0',
       'region_code_47.0', 'region_code_48.0', 'region_code_49.0',
       'region_code_50.0', 'region_code_51.0', 'region_code_52.0',
       'sexo_feminino'],
      dtype='object', length=211)

In [ ]:
from sklearn.tree import DecisionTreeClassifier 
df_train_2 = df_to_model
inference_cols = [x for x in df_to_model.columns if x not in ('Response','Gender')]
model = DecisionTreeClassifier(criterion='entropy',)
model.fit(X = df_to_model.loc[:, inference_cols],
          y = df_to_model['Response'])

DecisionTreeClassifier(criterion='entropy')

In [84]:
importancies = model.feature_importances_
importancies = dict(zip(inference_cols , model.feature_importances_))
df_importancies = pd.DataFrame(importancies,
             index = [0]).T

df_importancies.columns = ['score']
df_importancies = df_importancies.reset_index(drop = False)
df_importancies = df_importancies.rename(columns={'0' : 'socre'})
df_importancies = df_importancies.sort_values(by = 'score',
                                              ascending=False)


df_importancies.reset_index()

     level_0                       index     score
0          5              Annual_Premium  0.365810
1          2          Previously_Insured  0.224499
2          0                         Age  0.126824
3        208               sexo_feminino  0.029569
4          4              Vehicle_Damage  0.028119
5          3                 Vehicle_Age  0.011920
6        183            region_code_28.0  0.011805
7        121  policy_sales_channel_124.0  0.008831
8        163             region_code_8.0  0.007479
9        201            region_code_46.0  0.007078
10         6                faixa_etaria  0.006649
11        31   policy_sales_channel_26.0  0.005400
12       170            region_code_15.0  0.005266
13       158             region_code_3.0  0.005093
14       196            region_code_41.0  0.004922
15       119  policy_sales_channel_122.0  0.004798
16       145  policy_sales_channel_152.0  0.004525
17       166            region_code_11.0  0.004495
18       147  policy_sales_channel_154.0  0.004175
19       185            region_code_30.0  0.004066
20       149  policy_sales_channel_156.0  0.003999
21       202            region_code_47.0  0.003865
22       150  policy_sales_channel_157.0  0.003819
23       184            region_code_29.0  0.003736
24       191            region_code_36.0  0.003732
25       188            region_code_33.0  0.003701
26       153  policy_sales_channel_160.0  0.003677
27       173            region_code_18.0  0.003668
28       194            region_code_39.0  0.003436
29       200            region_code_45.0  0.003419
30       190            region_code_35.0  0.003333
31       205            region_code_50.0  0.002853
32       192            region_code_37.0  0.002834
33       169            region_code_14.0  0.002778
34       162             region_code_7.0  0.002640
35       193            region_code_38.0  0.002488
36       161             region_code_6.0  0.002407
37       168            region_code_13.0  0.002371
38       157             region_code_2.0  0.002341
39       198            region_code_43.0  0.002199
40       164             region_code_9.0  0.002136
41       179            region_code_24.0  0.002079
42       159             region_code_4.0  0.002027
43       176            region_code_21.0  0.002016
44       167            region_code_12.0  0.001940
45       154  policy_sales_channel_163.0  0.001904
46       165            region_code_10.0  0.001818
47       187            region_code_32.0  0.001787
48       178            region_code_23.0  0.001701
49       172            region_code_17.0  0.001695
50        18   policy_sales_channel_13.0  0.001612
51       182            region_code_27.0  0.001590
52       148  policy_sales_channel_155.0  0.001575
53       181            region_code_26.0  0.001513
54       174            region_code_19.0  0.001416
55       195            region_code_40.0  0.001351
56        58   policy_sales_channel_55.0  0.001332
57        30   policy_sales_channel_25.0  0.001330
58       203            region_code_48.0  0.001309
59       160             region_code_5.0  0.001262
60       204            region_code_49.0  0.001218
61       186            region_code_31.0  0.001210
62       189            region_code_34.0  0.001171
63        34   policy_sales_channel_30.0  0.001128
64       180            region_code_25.0  0.001125
65        35   policy_sales_channel_31.0  0.001089
66       171            region_code_16.0  0.001010
67       175            region_code_20.0  0.000970
68       122  policy_sales_channel_125.0  0.000899
69        13    policy_sales_channel_8.0  0.000891
70        10    policy_sales_channel_4.0  0.000877
71        29   policy_sales_channel_24.0  0.000846
72       155             region_code_0.0  0.000832
73         9    policy_sales_channel_3.0  0.000812
74       177            region_code_22.0  0.000765
75       151  policy_sales_channel_158.0  0.000744
76        12    policy_sales_channel_7.0  0.000731
77        55   policy_sales_channel_52.0  0.000721
78       143  policy_sales_channel_150.0  0.000692
79        16   policy_sales_channel_11.0  0.000677
80        33   policy_sales_channel_29.0  0.000656
81       156             region_code_1.0  0.000627
82        64   policy_sales_channel_61.0  0.000568
83         1             Driving_License  0.000557
84       144  policy_sales_channel_151.0  0.000550
85        17   policy_sales_channel_12.0  0.000535
86        63   policy_sales_channel_60.0  0.000503
87       197            region_code_42.0  0.000493
88        19   policy_sales_channel_14.0  0.000455
89        28   policy_sales_channel_23.0  0.000430
90       117  policy_sales_channel_120.0  0.000388
91       207            region_code_52.0  0.000387
92       146  policy_sales_channel_153.0  0.000374
93         7    policy_sales_channel_1.0  0.000320
94       199            region_code_44.0  0.000303
95       206            region_code_51.0  0.000277
96        20   policy_sales_channel_15.0  0.000267
97       141  policy_sales_channel_147.0  0.000252
98        24   policy_sales_channel_19.0  0.000237
99        21   policy_sales_channel_16.0  0.000233
100      113  policy_sales_channel_116.0  0.000232
101      133  policy_sales_channel_136.0  0.000229
102       45   policy_sales_channel_42.0  0.000227
103       62   policy_sales_channel_59.0  0.000219
104      128  policy_sales_channel_131.0  0.000198
105       47   policy_sales_channel_44.0  0.000196
106       15   policy_sales_channel_10.0  0.000156
107      118  policy_sales_channel_121.0  0.000140
108       14    policy_sales_channel_9.0  0.000139
109       88   policy_sales_channel_91.0  0.000138
110       26   policy_sales_channel_21.0  0.000130
111       27   policy_sales_channel_22.0  0.000130
112      106  policy_sales_channel_109.0  0.000121
113      139  policy_sales_channel_145.0  0.000119
114       40   policy_sales_channel_36.0  0.000118
115       41   policy_sales_channel_37.0  0.000115
116      125  policy_sales_channel_128.0  0.000107
117      130  policy_sales_channel_133.0  0.000103
118      135  policy_sales_channel_138.0  0.000098
119       59   policy_sales_channel_56.0  0.000097
120       91   policy_sales_channel_94.0  0.000094
121      142  policy_sales_channel_148.0  0.000092
122      132  policy_sales_channel_135.0  0.000089
123       80   policy_sales_channel_81.0  0.000082
124       48   policy_sales_channel_45.0  0.000082
125      136  policy_sales_channel_139.0  0.000078
126       23   policy_sales_channel_18.0  0.000077
127       57   policy_sales_channel_54.0  0.000075
128       67   policy_sales_channel_64.0  0.000073
129       50   policy_sales_channel_47.0  0.000072
130      100  policy_sales_channel_103.0  0.000070
131      137  policy_sales_channel_140.0  0.000066
132       25   policy_sales_channel_20.0  0.000065
133       68   policy_sales_channel_65.0  0.000062
134       79   policy_sales_channel_80.0  0.000060
135      124  policy_sales_channel_127.0  0.000060
136       39   policy_sales_channel_35.0  0.000057
137      108  policy_sales_channel_111.0  0.000055
138       51   policy_sales_channel_48.0  0.000052
139      103  policy_sales_channel_106.0  0.000049
140      111  policy_sales_channel_114.0  0.000046
141      129  policy_sales_channel_132.0  0.000044
142       83   policy_sales_channel_86.0  0.000043
143       44   policy_sales_channel_40.0  0.000042
144       56   policy_sales_channel_53.0  0.000040
145       85   policy_sales_channel_88.0  0.000037
146       87   policy_sales_channel_90.0  0.000035
147      110  policy_sales_channel_113.0  0.000035
148       89   policy_sales_channel_92.0  0.000035
149       97  policy_sales_channel_100.0  0.000032
150       86   policy_sales_channel_89.0  0.000030
151      140  policy_sales_channel_146.0  0.000029
152      126  policy_sales_channel_129.0  0.000028
153       36   policy_sales_channel_32.0  0.000025
154       98  policy_sales_channel_101.0  0.000024
155       75   policy_sales_channel_73.0  0.000022
156       52   policy_sales_channel_49.0  0.000022
157       61   policy_sales_channel_58.0  0.000021
158      116  policy_sales_channel_119.0  0.000019
159       22   policy_sales_channel_17.0  0.000019
160       95   policy_sales_channel_98.0  0.000018
161       94   policy_sales_channel_97.0  0.000017
162      107  policy_sales_channel_110.0  0.000017
163       77   policy_sales_channel_78.0  0.000016
164       46   policy_sales_channel_43.0  0.000014
165      120  policy_sales_channel_123.0  0.000013
166      152  policy_sales_channel_159.0  0.000009
167       60   policy_sales_channel_57.0  0.000007
168       93   policy_sales_channel_96.0  0.000004
169      115  policy_sales_channel_118.0  0.000004
170      134  policy_sales_channel_137.0  0.000003
171       54   policy_sales_channel_51.0  0.000000
172        8    policy_sales_channel_2.0  0.000000
173       43   policy_sales_channel_39.0  0.000000
174       53   policy_sales_channel_50.0  0.000000
175       38   policy_sales_channel_34.0  0.000000
176       37   policy_sales_channel_33.0  0.000000
177       49   policy_sales_channel_46.0  0.000000
178       42   policy_sales_channel_38.0  0.000000
179       32   policy_sales_channel_27.0  0.000000
180       11    policy_sales_channel_6.0  0.000000
181      112  policy_sales_channel_115.0  0.000000
182       65   policy_sales_channel_62.0  0.000000
183       90   policy_sales_channel_93.0  0.000000
184      109  policy_sales_channel_112.0  0.000000
185      123  policy_sales_channel_126.0  0.000000
186      127  policy_sales_channel_130.0  0.000000
187      105  policy_sales_channel_108.0  0.000000
188      131  policy_sales_channel_134.0  0.000000
189      138  policy_sales_channel_144.0  0.000000
190      102  policy_sales_channel_105.0  0.000000
191      101  policy_sales_channel_104.0  0.000000
192       99  policy_sales_channel_102.0  0.000000
193       96   policy_sales_channel_99.0  0.000000
194       92   policy_sales_channel_95.0  0.000000
195       84   policy_sales_channel_87.0  0.000000
196       66   policy_sales_channel_63.0  0.000000
197      114  policy_sales_channel_117.0  0.000000
198       82   policy_sales_channel_83.0  0.000000
199       81   policy_sales_channel_82.0  0.000000
200       78   policy_sales_channel_79.0  0.000000
201       76   policy_sales_channel_76.0  0.000000
202       74   policy_sales_channel_71.0  0.000000
203       73   policy_sales_channel_70.0  0.000000
204       72   policy_sales_channel_69.0  0.000000
205       71   policy_sales_channel_68.0  0.000000
206       70   policy_sales_channel_67.0  0.000000
207       69   policy_sales_channel_66.0  0.000000
208      104  policy_sales_channel_107.0  0.000000

In [67]:
model.feature_importances_

array([2.86508511e-01, 1.12275127e-01, 6.77717682e-04, 1.26024980e-02,
       1.09860004e-02, 1.24431478e-01, 2.18009181e-01, 6.64551332e-03,
       1.16799544e-04, 2.43542741e-05, 7.21728220e-04, 8.59773185e-04,
       0.00000000e+00, 6.79222666e-04, 5.31740154e-04, 1.13688029e-04,
       2.64351527e-04, 7.80669243e-04, 3.48979458e-04, 1.65399382e-03,
       5.65956316e-04, 4.39384102e-04, 2.69394037e-04, 2.55716659e-05,
       1.01477097e-04, 1.71981380e-04, 4.61326317e-05, 1.67734277e-04,
       1.45102928e-04, 3.73798641e-04, 8.73116789e-04, 1.03209715e-03,
       4.65296848e-03, 0.00000000e+00, 8.40969357e-04, 8.66319899e-04,
       1.15958248e-03, 4.79104027e-05, 0.00000000e+00, 0.00000000e+00,
       5.03799138e-05, 7.59492515e-05, 1.42904015e-04, 0.00000000e+00,
       0.00000000e+00, 2.40598136e-05, 2.11069986e-04, 2.23934212e-05,
       2.19976800e-04, 1.01602996e-04, 1.71158409e-05, 6.31923342e-05,
       2.90450633e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       7.40208615e-04, 0.00000000e+00, 1.18426154e-04, 1.32393005e-03,
       1.05352720e-04, 0.00000000e+00, 2.77564689e-05, 1.39869951e-04,
       5.46393108e-04, 3.28453894e-04, 0.00000000e+00, 2.58338095e-05,
       4.59721629e-05, 7.83220878e-05, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.54275693e-05, 0.00000000e+00,
       7.76697367e-05, 5.98182082e-05, 0.00000000e+00, 0.00000000e+00,
       5.55212450e-05, 0.00000000e+00, 0.00000000e+00, 2.40774383e-05,
       6.38516404e-05, 1.87239966e-04, 2.98255149e-05, 3.53902925e-05,
       9.81688374e-05, 0.00000000e+00, 0.00000000e+00, 2.75818690e-05,
       0.00000000e+00, 0.00000000e+00, 2.58847122e-05, 3.88631484e-05,
       0.00000000e+00, 8.40694553e-05, 0.00000000e+00, 0.00000000e+00,
       4.93258378e-05, 0.00000000e+00, 0.00000000e+00, 2.49214520e-04,
       2.55596557e-05, 5.76680456e-05, 0.00000000e+00, 4.26760948e-05,
       5.78371094e-05, 0.00000000e+00, 1.61979354e-04, 0.00000000e+00,
       2.55596557e-05, 2.56704629e-05, 3.32175661e-04, 5.89498853e-05,
       4.86027866e-03, 0.00000000e+00, 8.09499383e-03, 9.76841909e-04,
       0.00000000e+00, 4.82472845e-05, 4.85633458e-05, 5.48776173e-05,
       0.00000000e+00, 5.11193114e-05, 6.42688754e-05, 2.94468533e-05,
       0.00000000e+00, 7.34128998e-05, 3.00591311e-04, 0.00000000e+00,
       1.56506884e-04, 1.15345276e-04, 9.18379841e-05, 0.00000000e+00,
       1.70010794e-04, 0.00000000e+00, 3.49280739e-04, 5.11526355e-05,
       6.73382788e-04, 4.58300486e-04, 4.31947581e-03, 3.42210238e-04,
       3.78650649e-03, 1.42871938e-03, 3.85360334e-03, 4.27405004e-03,
       7.66562533e-04, 5.90521557e-05, 3.11544522e-03, 2.27593776e-03,
       8.56555373e-04, 8.77308776e-04, 1.99094806e-03, 5.37690849e-03,
       1.59503347e-03, 9.46739781e-04, 1.84706147e-03, 2.46625596e-03,
       7.79590340e-03, 2.02271534e-03, 1.60387253e-03, 4.07096768e-03,
       2.23465814e-03, 2.47655778e-03, 2.79120435e-03, 4.32455067e-03,
       8.44608775e-04, 1.33596561e-03, 3.40557888e-03, 1.40641913e-03,
       1.12355400e-03, 1.65399723e-03, 6.16953012e-04, 2.08360261e-03,
       2.06975503e-03, 1.01225918e-03, 1.65545992e-03, 1.27306400e-03,
       1.17216121e-02, 4.38200514e-03, 4.72489892e-03, 1.08494491e-03,
       1.46456781e-03, 4.38659456e-03, 1.30535650e-03, 3.32332005e-03,
       3.63477682e-03, 2.36182090e-03, 2.76511409e-03, 3.51833413e-03,
       1.34188065e-03, 6.20710745e-03, 4.19330551e-04, 1.83611268e-03,
       3.09536756e-04, 3.13070185e-03, 7.84865542e-03, 3.51273157e-03,
       1.65493809e-03, 1.12353920e-03, 2.76969505e-03, 2.94292050e-04,
       3.14815242e-04, 2.55357976e-02])

# 4 - Treinamento dos modelos

In [68]:
# trbalhar com as colunas abaixo
# Age, 
# Vehichle_Age
# Annual Premium 
# vintage, 
# Response