# Desafio

A empresa Você Mais Seguro fornece planos de saúde e seguros de vida. 
A empresa está interessada em lança um novo seguro de veiculos, e desja entender a propensão de compra de seus clientes para este novo cenário. 
Em uma primeira etapa, foi realizada uma grande pesquisa com seus cleintes, para entender quais destes clientes estariam interessados em adquirir o novo seguro de veiculos.

Agora, com novos clientes do plano de saude entrando para sua base, a empresa deseja entender quais destes novos clientes teriam maior propensão de compra do novo seguro de veiculos.
No entanto, a empresa não esta interessada em gastar com pesquisas para todos os novos clientes, e sim apenas para aqueles que tem maior propensão de compra, 
haja visto,que seu efetivo comercial, não é capaz de entrar em contato, para fornecer um processo de pré vendas personalizado para toda a base de seus novos clientes, somente
para 2000 deles de cada vez. 

Para isso, este projeto tem como objetivo apresentar uma lista, com os 2000 clientes com maior probabilidade de venda do seguro de veículos.

# 0.0 Imports

In [1]:
import pandas as pd 
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

### 0.1 Helper Functions

In [2]:
def jupyter_settings():
    %matplotlib inline
    %pylab inline

    plt.style.use( 'bmh' )
    plt.rcParams['figure.figsize'] = [25, 8]
    plt.rcParams['font.size'] = 24
    pd.options.display.max_columns = None
    pd.options.display.max_rows = None
    pd.set_option( 'display.expand_frame_repr', False )
    sns.set()

jupyter_settings()

def print_descriptive_stats(df,
                            column):
    print(f'**Clientes que adquiririam o Seguro - {column} statistics**')
    print(df[df.Response == 1][column].describe())
    print('-'*45)
    print(f'**Clientes NAO que adquiririam o Seguro - {column} statistics**')
    print(df[df.Response == 0][column].describe())
    print('\n')

def get_frequency_table(df, column): 

    df_frequency_1 = df[df.Response == 1].groupby(column).Response.count().reset_index()
    df_frequency_1.rename(columns={'Response':'Count_Response_1'}, inplace=True)


    df_frequency_0 = df[df.Response == 0].groupby(column).Response.count().reset_index()
    df_frequency_0.rename(columns={'Response':'Count_Response_0'}, inplace=True)

    df_frequency = pd.merge(df_frequency_1, df_frequency_0, on=column, how='inner') 
    df_frequency['Total'] = df_frequency['Count_Response_1'] + df_frequency['Count_Response_0']
    df_frequency['Propensity_to_buy'] = df_frequency['Count_Response_1']/df_frequency['Total']
    df_frequency['%_sample_to_buy'] = df_frequency['Count_Response_1']/df_frequency['Count_Response_1'].sum() 
    df_frequency['%_sample_to_not_buy'] = df_frequency['Count_Response_0']/df_frequency['Count_Response_0'].sum() 
    df_frequency['%_sample_size']   = df_frequency['Total']/len(df)
    df_frequency['%_general_propensity_to_buy'] = len(df[df.Response==1])/len(df)
    
    return df_frequency


def transform_pipeline(df):

    '''
    [EM FASE DE VALIDACAO....]
    '''
    from sklearn.preprocessing import StandardScaler, MinMaxScaler 


    region_code = df.Region_Code.copy()
    dummies_region_code = pd.get_dummies(region_code,prefix = "region_code")

    sales_channel = df.Policy_Sales_Channel.copy()
    dummies_sales_channel = pd.get_dummies(sales_channel,prefix = "policy_sales_channel")

    df_copy = df.copy()
    df_encoded = pd.concat([df_copy, dummies_sales_channel, dummies_region_code], axis = 1)


    df_encoded.drop(columns = ['Region_Code','Policy_Sales_Channel'], inplace = True)

    map_sexo_feminino = {
        'Male' : 0,
        'Female' : 1 
    }

    df_encoded['sexo_feminino'] = df_encoded.Gender.map(map_sexo_feminino)


    df_encoded.Vehicle_Damage = df_encoded.Vehicle_Damage.map({
        'Yes' : 1,
        'No'  : 0
    })


    scaller_premium      = MinMaxScaler()
    scaller_vintage      = MinMaxScaler()
    scaller_age          = MinMaxScaler()
    scaller_faixa_etaria = MinMaxScaler()

    df_encoded.Vintage_Scalled        = scaller_vintage.fit_transform(df_encoded.Vintage.values.reshape(-1,1))
    df_encoded.Annual_Premium_Scalled = scaller_premium.fit_transform(df_encoded.Annual_Premium.values.reshape(-1,1))


    df_encoded.Age        = scaller_age.fit_transform(df_encoded.Age.values.reshape(-1,1))
    df_encoded.faixa_etaria        = scaller_faixa_etaria.fit_transform(df_encoded.faixa_etaria.values.reshape(-1,1))


    df_encoded.Annual_Premium.describe()

    df_to_model = df_encoded[[x for x in df_encoded.columns if x not in ['id','Vintage_months','Vintage_weeks','Vintage']]]
    df_to_model.columns
    return df_to_model

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

# 1.0 Limpeza dos Dados

**Tipos de limpezas**

* Nulos
* Tipagem inconsistente 
* Claros outliers (indicio de erro de digitação)

### 1.1 - Conhecendo o Dataset

In [3]:
df_raw = pd.read_csv('../data/raw/data.csv')
df_raw.head()

   id  Gender  Age  Driving_License  Region_Code  Previously_Insured Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  Response
0   1    Male   44                1         28.0                   0   > 2 Years            Yes         40454.0                  26.0      217         1
1   2    Male   76                1          3.0                   0    1-2 Year             No         33536.0                  26.0      183         0
2   3    Male   47                1         28.0                   0   > 2 Years            Yes         38294.0                  26.0       27         1
3   4    Male   21                1         11.0                   1    < 1 Year             No         28619.0                 152.0      203         0
4   5  Female   29                1         41.0                   1    < 1 Year             No         27496.0                 152.0       39         0

# 3.0 - Preparação dos dados

In [4]:
df_3 = df_raw.copy()
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381109 entries, 0 to 381108
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    381109 non-null  int64
 1   Gender                381109 non-null  object
 2   Age                   381109 non-null  int64
 3   Driving_License       381109 non-null  int64
 4   Region_Code           381109 non-null  float64
 5   Previously_Insured    381109 non-null  int64
 6   Vehicle_Age           381109 non-null  object
 7   Vehicle_Damage        381109 non-null  object
 8   Annual_Premium        381109 non-null  float64
 9   Policy_Sales_Channel  381109 non-null  float64
 10  Vintage               381109 non-null  int64
 11  Response              381109 non-null  int64
dtypes: float64(3), int64(6), object(3)
memory usage: 34.9+ MB

### 3.1 - Criação de features

* Faixa etaria
* Tem entre 30 - 50 anos (EDA)

In [5]:
df_3['faixa_etaria'] = df_3.Age.apply(lambda x: 10*(x//10))
df_3['entre_30_50'] = df_3.Age.apply(lambda x: 1 if (x>=30) and (x<=50) else 0)

### 3.1 - Encodings

#### 3.1.1 - One Hot Encoding (dummi)

* Policy Sales Channel 
* Region Code

**Region Code**

A justificativa se da pela ausencia de elação quantitativa nos dados de region code. 

A regiao "102" ser maior que a regiao "32" não faz sentido

In [6]:
region_code = df_3.Region_Code.copy()
dummies_region_code = pd.get_dummies(region_code,prefix = "region_code")
dummies_region_code.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381109 entries, 0 to 381108
Data columns (total 53 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   region_code_0.0   381109 non-null  bool
 1   region_code_1.0   381109 non-null  bool
 2   region_code_2.0   381109 non-null  bool
 3   region_code_3.0   381109 non-null  bool
 4   region_code_4.0   381109 non-null  bool
 5   region_code_5.0   381109 non-null  bool
 6   region_code_6.0   381109 non-null  bool
 7   region_code_7.0   381109 non-null  bool
 8   region_code_8.0   381109 non-null  bool
 9   region_code_9.0   381109 non-null  bool
 10  region_code_10.0  381109 non-null  bool
 11  region_code_11.0  381109 non-null  bool
 12  region_code_12.0  381109 non-null  bool
 13  region_code_13.0  381109 non-null  bool
 14  region_code_14.0  381109 non-null  bool
 15  region_code_15.0  381109 non-null  bool
 16  region_code_16.0  381109 non-null  bool
 17  region_code_17.0  381109 non-null  bool
 18  region_code_18.0  381109 non-null  bool
 19  region_code_19.0  381109 non-null  bool
 20  region_code_20.0  381109 non-null  bool
 21  region_code_21.0  381109 non-null  bool
 22  region_code_22.0  381109 non-null  bool
 23  region_code_23.0  381109 non-null  bool
 24  region_code_24.0  381109 non-null  bool
 25  region_code_25.0  381109 non-null  bool
 26  region_code_26.0  381109 non-null  bool
 27  region_code_27.0  381109 non-null  bool
 28  region_code_28.0  381109 non-null  bool
 29  region_code_29.0  381109 non-null  bool
 30  region_code_30.0  381109 non-null  bool
 31  region_code_31.0  381109 non-null  bool
 32  region_code_32.0  381109 non-null  bool
 33  region_code_33.0  381109 non-null  bool
 34  region_code_34.0  381109 non-null  bool
 35  region_code_35.0  381109 non-null  bool
 36  region_code_36.0  381109 non-null  bool
 37  region_code_37.0  381109 non-null  bool
 38  region_code_38.0  381109 non-null  bool
 39  region_code_39.0  381109 non-null  bool
 40  region_code_40.0  381109 non-null  bool
 41  region_code_41.0  381109 non-null  bool
 42  region_code_42.0  381109 non-null  bool
 43  region_code_43.0  381109 non-null  bool
 44  region_code_44.0  381109 non-null  bool
 45  region_code_45.0  381109 non-null  bool
 46  region_code_46.0  381109 non-null  bool
 47  region_code_47.0  381109 non-null  bool
 48  region_code_48.0  381109 non-null  bool
 49  region_code_49.0  381109 non-null  bool
 50  region_code_50.0  381109 non-null  bool
 51  region_code_51.0  381109 non-null  bool
 52  region_code_52.0  381109 non-null  bool
dtypes: bool(53)
memory usage: 19.3 MB

**Policy Sales Channel**

In [7]:

sales_channel = df_3.Policy_Sales_Channel.copy()
dummies_sales_channel = pd.get_dummies(sales_channel,prefix = "policy_sales_channel")
dummies_sales_channel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381109 entries, 0 to 381108
Columns: 155 entries, policy_sales_channel_1.0 to policy_sales_channel_163.0
dtypes: bool(155)
memory usage: 56.3 MB

In [8]:
dummies_sales_channel.head(5)

   policy_sales_channel_1.0  policy_sales_channel_2.0  policy_sales_channel_3.0  policy_sales_channel_4.0  policy_sales_channel_6.0  policy_sales_channel_7.0  policy_sales_channel_8.0  policy_sales_channel_9.0  policy_sales_channel_10.0  policy_sales_channel_11.0  policy_sales_channel_12.0  policy_sales_channel_13.0  policy_sales_channel_14.0  policy_sales_channel_15.0  policy_sales_channel_16.0  policy_sales_channel_17.0  policy_sales_channel_18.0  policy_sales_channel_19.0  policy_sales_channel_20.0  policy_sales_channel_21.0  policy_sales_channel_22.0  policy_sales_channel_23.0  policy_sales_channel_24.0  policy_sales_channel_25.0  policy_sales_channel_26.0  policy_sales_channel_27.0  policy_sales_channel_28.0  policy_sales_channel_29.0  policy_sales_channel_30.0  policy_sales_channel_31.0  policy_sales_channel_32.0  policy_sales_channel_33.0  policy_sales_channel_34.0  policy_sales_channel_35.0  policy_sales_channel_36.0  policy_sales_channel_37.0  policy_sales_channel_38.0  policy_sales_channel_39.0  policy_sales_channel_40.0  policy_sales_channel_41.0  policy_sales_channel_42.0  policy_sales_channel_43.0  policy_sales_channel_44.0  policy_sales_channel_45.0  policy_sales_channel_46.0  policy_sales_channel_47.0  policy_sales_channel_48.0  policy_sales_channel_49.0  policy_sales_channel_50.0  policy_sales_channel_51.0  policy_sales_channel_52.0  policy_sales_channel_53.0  policy_sales_channel_54.0  policy_sales_channel_55.0  policy_sales_channel_56.0  policy_sales_channel_57.0  policy_sales_channel_58.0  policy_sales_channel_59.0  policy_sales_channel_60.0  policy_sales_channel_61.0  policy_sales_channel_62.0  policy_sales_channel_63.0  policy_sales_channel_64.0  policy_sales_channel_65.0  policy_sales_channel_66.0  policy_sales_channel_67.0  policy_sales_channel_68.0  policy_sales_channel_69.0  policy_sales_channel_70.0  policy_sales_channel_71.0  policy_sales_channel_73.0  policy_sales_channel_74.0  policy_sales_channel_75.0  policy_sales_channel_76.0  policy_sales_channel_78.0  policy_sales_channel_79.0  policy_sales_channel_80.0  policy_sales_channel_81.0  policy_sales_channel_82.0  policy_sales_channel_83.0  policy_sales_channel_84.0  policy_sales_channel_86.0  policy_sales_channel_87.0  policy_sales_channel_88.0  policy_sales_channel_89.0  policy_sales_channel_90.0  policy_sales_channel_91.0  policy_sales_channel_92.0  policy_sales_channel_93.0  policy_sales_channel_94.0  policy_sales_channel_95.0  policy_sales_channel_96.0  policy_sales_channel_97.0  policy_sales_channel_98.0  policy_sales_channel_99.0  policy_sales_channel_100.0  policy_sales_channel_101.0  policy_sales_channel_102.0  policy_sales_channel_103.0  policy_sales_channel_104.0  policy_sales_channel_105.0  policy_sales_channel_106.0  policy_sales_channel_107.0  policy_sales_channel_108.0  policy_sales_channel_109.0  policy_sales_channel_110.0  policy_sales_channel_111.0  policy_sales_channel_112.0  policy_sales_channel_113.0  policy_sales_channel_114.0  policy_sales_channel_115.0  policy_sales_channel_116.0  policy_sales_channel_117.0  policy_sales_channel_118.0  policy_sales_channel_119.0  policy_sales_channel_120.0  policy_sales_channel_121.0  policy_sales_channel_122.0  policy_sales_channel_123.0  policy_sales_channel_124.0  policy_sales_channel_125.0  policy_sales_channel_126.0  policy_sales_channel_127.0  policy_sales_channel_128.0  policy_sales_channel_129.0  policy_sales_channel_130.0  policy_sales_channel_131.0  policy_sales_channel_132.0  policy_sales_channel_133.0  policy_sales_channel_134.0  policy_sales_channel_135.0  policy_sales_channel_136.0  policy_sales_channel_137.0  policy_sales_channel_138.0  policy_sales_channel_139.0  policy_sales_channel_140.0  policy_sales_channel_143.0  policy_sales_channel_144.0  policy_sales_channel_145.0  policy_sales_channel_146.0  policy_sales_channel_147.0  policy_sales_channel_148.0  policy_sales_channel_149.0  policy_sales_channel_150.0  policy_sales_channel_151.0  policy_sales_channel_152.0  policy_sales_channel_153.0  policy_sales_channel_154.0  policy_sales_channel_155.0  policy_sales_channel_156.0  policy_sales_channel_157.0  policy_sales_channel_158.0  policy_sales_channel_159.0  policy_sales_channel_160.0  policy_sales_channel_163.0
0                     False                     False                     False                     False                     False                     False                     False                     False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                       True                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False
1                     False                     False                     False                     False                     False                     False                     False                     False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                       True                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False
2                     False                     False                     False                     False                     False                     False                     False                     False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                       True                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                      False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False                       False

**Merge ao dataset original**

In [9]:
df_3_copy = df_3.copy()
df_3_encoded = pd.concat([df_3_copy, dummies_sales_channel, dummies_region_code], axis = 1)


df_3_encoded.drop(columns = ['Region_Code','Policy_Sales_Channel'], inplace = True)
df_3_encoded.shape

(381109, 220)

**Region Code**

#### 3.1.2 - Binary Encoding

* Gender
* Driving License
* Previously Insured
* Vehicle Damage
* Response

In [10]:
df_3_encoded.Gender.value_counts()

Gender
Male      206089
Female    175020
Name: count, dtype: int64

In [11]:

map_sexo_feminino = {
    'Male' : 0,
    'Female' : 1 
}

df_3_encoded['sexo_feminino'] = df_3_encoded.Gender.map(map_sexo_feminino)

**Checagem dos demais campos**

In [12]:
df_3_encoded.Driving_License.value_counts()

Driving_License
1    380297
0       812
Name: count, dtype: int64

In [13]:
df_3_encoded.Previously_Insured.value_counts()

Previously_Insured
0    206481
1    174628
Name: count, dtype: int64

In [14]:
df_3_encoded.Vehicle_Damage.value_counts()

Vehicle_Damage
Yes    192413
No     188696
Name: count, dtype: int64

In [15]:
df_3_encoded.Vehicle_Damage = df_3_encoded.Vehicle_Damage.map({
    'Yes' : 1,
    'No'  : 0
})

df_3_encoded.Vehicle_Damage.value_counts()

Vehicle_Damage
1    192413
0    188696
Name: count, dtype: int64

In [16]:
df_3_encoded.Response.value_counts()

Response
0    334399
1     46710
Name: count, dtype: int64

### 3.1.3 - Ordinal Encoding

In [17]:
df_3_encoded.loc[:,'Vehicle_Age'] = df_3_encoded.loc[:,'Vehicle_Age'].map({'< 1 Year':0, '1-2 Year':1, '> 2 Years':2})

## 3.2 - Variaveis Numéricas (Padronização,  Normalização, transformação ciclica, etc.)

In [18]:
df_3_encoded[[x for x in df_3_encoded.columns if '.0' not in x]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381109 entries, 0 to 381108
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  381109 non-null  int64
 1   Gender              381109 non-null  object
 2   Age                 381109 non-null  int64
 3   Driving_License     381109 non-null  int64
 4   Previously_Insured  381109 non-null  int64
 5   Vehicle_Age         381109 non-null  object
 6   Vehicle_Damage      381109 non-null  int64
 7   Annual_Premium      381109 non-null  float64
 8   Vintage             381109 non-null  int64
 9   Response            381109 non-null  int64
 10  faixa_etaria        381109 non-null  int64
 11  entre_30_50         381109 non-null  int64
 12  sexo_feminino       381109 non-null  int64
dtypes: float64(1), int64(10), object(2)
memory usage: 37.8+ MB

In [19]:
df_3_encoded.Vintage.values.shape

(381109,)

In [20]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler 


scaller_premium      = MinMaxScaler()
scaller_vintage      = MinMaxScaler()
scaller_age          = MinMaxScaler()
scaller_faixa_etaria = MinMaxScaler()

df_3_encoded.Vintage_Scalled        = scaller_vintage.fit_transform(df_3_encoded.Vintage.values.reshape(-1,1))
df_3_encoded.Annual_Premium_Scalled = scaller_premium.fit_transform(df_3_encoded.Annual_Premium.values.reshape(-1,1))


df_3_encoded.Age        = scaller_age.fit_transform(df_3_encoded.Age.values.reshape(-1,1))
df_3_encoded.faixa_etaria        = scaller_faixa_etaria.fit_transform(df_3_encoded.faixa_etaria.values.reshape(-1,1))


df_3_encoded.Annual_Premium.describe()

/tmp/ipykernel_7346/850787241.py:9: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_3_encoded.Vintage_Scalled        = scaller_vintage.fit_transform(df_3_encoded.Vintage.values.reshape(-1,1))
/tmp/ipykernel_7346/850787241.py:10: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_3_encoded.Annual_Premium_Scalled = scaller_premium.fit_transform(df_3_encoded.Annual_Premium.values.reshape(-1,1))

count    381109.000000
mean      30564.389581
std       17213.155057
min        2630.000000
25%       24405.000000
50%       31669.000000
75%       39400.000000
max      540165.000000
Name: Annual_Premium, dtype: float64

In [21]:
df_to_model = df_3_encoded[[x for x in df_3_encoded.columns if x not in ['id','Vintage_months','Vintage_weeks','Vintage']]]
df_to_model.columns

Index(['Gender', 'Age', 'Driving_License', 'Previously_Insured', 'Vehicle_Age',
       'Vehicle_Damage', 'Annual_Premium', 'Response', 'faixa_etaria',
       'entre_30_50',
       ...
       'region_code_44.0', 'region_code_45.0', 'region_code_46.0',
       'region_code_47.0', 'region_code_48.0', 'region_code_49.0',
       'region_code_50.0', 'region_code_51.0', 'region_code_52.0',
       'sexo_feminino'],
      dtype='object', length=219)

### 3.3 - Seleção de variaveis

In [22]:
def transform_pipeline(df):

    '''
    [EM FASE DE VALIDACAO....]
    '''
    from sklearn.preprocessing import StandardScaler, MinMaxScaler 


    region_code = df.Region_Code.copy()
    dummies_region_code = pd.get_dummies(region_code,prefix = "region_code")

    sales_channel = df.Policy_Sales_Channel.copy()
    dummies_sales_channel = pd.get_dummies(sales_channel,prefix = "policy_sales_channel")

    df_copy = df.copy()
    df_encoded = pd.concat([df_copy, dummies_sales_channel, dummies_region_code], axis = 1)

    df_encoded.loc[:,'Vehicle_Age'] = df_encoded.loc[:,'Vehicle_Age'].map({'< 1 Year':0, '1-2 Year':1, '> 2 Years':2})


    df_encoded.drop(columns = ['Region_Code','Policy_Sales_Channel'], inplace = True)

    map_sexo_feminino = {
        'Male' : 0,
        'Female' : 1 
    }

    df_encoded['sexo_feminino'] = df_encoded.Gender.map(map_sexo_feminino)


    df_encoded.Vehicle_Damage = df_encoded.Vehicle_Damage.map({
        'Yes' : 1,
        'No'  : 0
    })


    scaller_premium      = MinMaxScaler()
    scaller_vintage      = MinMaxScaler()
    scaller_age          = MinMaxScaler()
    scaller_faixa_etaria = MinMaxScaler()

    df_encoded.Vintage_Scalled        = scaller_vintage.fit_transform(df_encoded.Vintage.values.reshape(-1,1))
    df_encoded.Annual_Premium_Scalled = scaller_premium.fit_transform(df_encoded.Annual_Premium.values.reshape(-1,1))


    df_encoded.Age        = scaller_age.fit_transform(df_encoded.Age.values.reshape(-1,1))
    df_encoded.faixa_etaria        = scaller_faixa_etaria.fit_transform(df_encoded.faixa_etaria.values.reshape(-1,1))


    df_encoded.Annual_Premium.describe()

    df_to_model = df_encoded[[x for x in df_encoded.columns if x not in ['id','Vintage_months','Vintage_weeks','Vintage']]]

    return df_to_model

#df_to_model = transform_pipeline(df_raw)

In [23]:
from sklearn.tree import DecisionTreeClassifier
df_to_model = df_3_encoded.copy()
df_to_model_train, df_to_model_test = train_test_split(df_to_model, test_size=0.3, 
                                                       random_state=42, stratify=df_to_model['Response'])

inference_cols = [x for x in df_to_model.columns if x not in ('Response','Gender')]
model = DecisionTreeClassifier(criterion='entropy',)
model.fit(X = df_to_model_train.loc[:, inference_cols],
          y = df_to_model_train['Response'])

DecisionTreeClassifier(criterion='entropy')

In [54]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()
logistic_model.fit(X = df_to_model_train.loc[:, inference_cols],
                     y = df_to_model_train['Response'])

/home/p123/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [31]:
y_pred = logistic_model.predict_proba(df_to_model_test.loc[:, inference_cols])
y_pred

array([[0.9969883 , 0.0030117 ],
       [0.86156091, 0.13843909],
       [0.99850084, 0.00149916],
       ...,
       [0.79947649, 0.20052351],
       [0.99772313, 0.00227687],
       [0.95013694, 0.04986306]])

In [48]:
def custom_predict(model,
                   data,
                   threshold=0.5):
    
    y_hat = model.predict_proba(data)

    return (y_hat[:, 1] > threshold).astype(int)

In [56]:
logistic_model.predict_proba(df_to_model_test.loc[:, inference_cols])

array([[0.9969883 , 0.0030117 ],
       [0.86156091, 0.13843909],
       [0.99850084, 0.00149916],
       ...,
       [0.79947649, 0.20052351],
       [0.99772313, 0.00227687],
       [0.95013694, 0.04986306]])

In [ ]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score , confusion_matrix

y_pred = custom_predict(model = logistic_model,
                        data = df_to_model_test.loc[:, inference_cols])

accuracy = accuracy_score(df_to_model_test['Response'],     y_pred=y_pred)
f1_score = f1_score(df_to_model_test['Response'],           y_pred=y_pred)
precision = precision_score(df_to_model_test['Response'],   y_pred=y_pred)
recall = recall_score(df_to_model_test['Response'],         y_pred=y_pred)

confusion_matrix = confusion_matrix(df_to_model_test['Response'], y_pred=y_pred)

print(f'Accuracy: {accuracy:.4f} | F1 Score: {f1_score:.4f} | Precision: {precision:.4f} | Recall: {recall:.4f}')

Accuracy: 0.8764 | F1 Score: 0.0079 | Precision: 0.2478 | Recall: 0.0040

In [46]:
confusion_matrix

array([[90223, 10097],
       [ 9791,  4222]])

In [27]:
df_to_model.Response.value_counts()

Response
0    334399
1     46710
Name: count, dtype: int64

In [28]:
importancies = model.feature_importances_
importancies = dict(zip(inference_cols , model.feature_importances_))
df_importancies = pd.DataFrame(importancies,
             index = [0]).T

df_importancies.columns = ['score']
df_importancies = df_importancies.reset_index(drop = False)
df_importancies = df_importancies.rename(columns={'0' : 'socre'})
df_importancies = df_importancies.sort_values(by = 'score',
                                              ascending=False)


df_importancies.reset_index()

     level_0                       index     score
0          3          Previously_Insured  0.213793
1          0                          id  0.186645
2          7                     Vintage  0.160645
3          6              Annual_Premium  0.152246
4          1                         Age  0.062409
5          5              Vehicle_Damage  0.026603
6          9                 entre_30_50  0.017736
7        218               sexo_feminino  0.015447
8        193            region_code_28.0  0.009766
9        129  policy_sales_channel_124.0  0.007262
10         4                 Vehicle_Age  0.007234
11       173             region_code_8.0  0.006926
12       211            region_code_46.0  0.005296
13       206            region_code_41.0  0.004886
14        34   policy_sales_channel_26.0  0.004067
15       180            region_code_15.0  0.003826
16       157  policy_sales_channel_154.0  0.003790
17       163  policy_sales_channel_160.0  0.003682
18       127  policy_sales_channel_122.0  0.003662
19       160  policy_sales_channel_157.0  0.003619
20         8                faixa_etaria  0.003613
21       194            region_code_29.0  0.003548
22       155  policy_sales_channel_152.0  0.003473
23       168             region_code_3.0  0.003350
24       176            region_code_11.0  0.003225
25       183            region_code_18.0  0.002868
26       200            region_code_35.0  0.002844
27       210            region_code_45.0  0.002833
28       159  policy_sales_channel_156.0  0.002823
29       212            region_code_47.0  0.002779
30       195            region_code_30.0  0.002768
31       198            region_code_33.0  0.002419
32       201            region_code_36.0  0.002392
33       172             region_code_7.0  0.002118
34       204            region_code_39.0  0.002088
35       179            region_code_14.0  0.001939
36       171             region_code_6.0  0.001859
37       215            region_code_50.0  0.001764
38       202            region_code_37.0  0.001717
39       203            region_code_38.0  0.001649
40       177            region_code_12.0  0.001625
41       164  policy_sales_channel_163.0  0.001519
42       188            region_code_23.0  0.001478
43       189            region_code_24.0  0.001476
44       213            region_code_48.0  0.001456
45       178            region_code_13.0  0.001354
46       167             region_code_2.0  0.001324
47       186            region_code_21.0  0.001309
48        33   policy_sales_channel_25.0  0.001263
49       169             region_code_4.0  0.001238
50       184            region_code_19.0  0.001195
51       174             region_code_9.0  0.001193
52       175            region_code_10.0  0.001180
53       185            region_code_20.0  0.001168
54       192            region_code_27.0  0.001166
55        21   policy_sales_channel_13.0  0.001159
56       197            region_code_32.0  0.001132
57       208            region_code_43.0  0.001079
58       158  policy_sales_channel_155.0  0.001005
59       191            region_code_26.0  0.000930
60        63   policy_sales_channel_55.0  0.000926
61       205            region_code_40.0  0.000911
62       182            region_code_17.0  0.000887
63       170             region_code_5.0  0.000882
64       196            region_code_31.0  0.000882
65       199            region_code_34.0  0.000813
66        38   policy_sales_channel_30.0  0.000774
67       190            region_code_25.0  0.000730
68        12    policy_sales_channel_3.0  0.000658
69       181            region_code_16.0  0.000656
70       130  policy_sales_channel_125.0  0.000644
71       214            region_code_49.0  0.000641
72        16    policy_sales_channel_8.0  0.000637
73        60   policy_sales_channel_52.0  0.000635
74       165             region_code_0.0  0.000630
75       187            region_code_22.0  0.000541
76        39   policy_sales_channel_31.0  0.000533
77       161  policy_sales_channel_158.0  0.000530
78       154  policy_sales_channel_151.0  0.000512
79        32   policy_sales_channel_24.0  0.000505
80       166             region_code_1.0  0.000498
81        19   policy_sales_channel_11.0  0.000476
82        15    policy_sales_channel_7.0  0.000471
83        13    policy_sales_channel_4.0  0.000462
84         2             Driving_License  0.000462
85        22   policy_sales_channel_14.0  0.000326
86       153  policy_sales_channel_150.0  0.000292
87       125  policy_sales_channel_120.0  0.000279
88        31   policy_sales_channel_23.0  0.000253
89        37   policy_sales_channel_29.0  0.000250
90        24   policy_sales_channel_16.0  0.000248
91        69   policy_sales_channel_61.0  0.000247
92       209            region_code_44.0  0.000239
93        10    policy_sales_channel_1.0  0.000236
94        20   policy_sales_channel_12.0  0.000224
95       150  policy_sales_channel_147.0  0.000221
96        18   policy_sales_channel_10.0  0.000219
97       216            region_code_51.0  0.000204
98        23   policy_sales_channel_15.0  0.000198
99       156  policy_sales_channel_153.0  0.000182
100      217            region_code_52.0  0.000174
101      207            region_code_42.0  0.000160
102      141  policy_sales_channel_136.0  0.000159
103       68   policy_sales_channel_60.0  0.000152
104       27   policy_sales_channel_19.0  0.000151
105      114  policy_sales_channel_109.0  0.000144
106       96   policy_sales_channel_91.0  0.000142
107       52   policy_sales_channel_44.0  0.000141
108       45   policy_sales_channel_37.0  0.000128
109       30   policy_sales_channel_22.0  0.000126
110       44   policy_sales_channel_36.0  0.000112
111       64   policy_sales_channel_56.0  0.000108
112       67   policy_sales_channel_59.0  0.000105
113      148  policy_sales_channel_145.0  0.000102
114      121  policy_sales_channel_116.0  0.000101
115      118  policy_sales_channel_113.0  0.000064
116       29   policy_sales_channel_21.0  0.000055
117      126  policy_sales_channel_121.0  0.000049
118       87   policy_sales_channel_81.0  0.000046
119       91   policy_sales_channel_86.0  0.000043
120      132  policy_sales_channel_127.0  0.000043
121       98   policy_sales_channel_93.0  0.000041
122      124  policy_sales_channel_119.0  0.000040
123      137  policy_sales_channel_132.0  0.000040
124       43   policy_sales_channel_35.0  0.000040
125       74   policy_sales_channel_66.0  0.000037
126      134  policy_sales_channel_129.0  0.000036
127       73   policy_sales_channel_65.0  0.000035
128       48   policy_sales_channel_40.0  0.000034
129      140  policy_sales_channel_135.0  0.000033
130       53   policy_sales_channel_45.0  0.000033
131       61   policy_sales_channel_53.0  0.000032
132       95   policy_sales_channel_90.0  0.000031
133      108  policy_sales_channel_103.0  0.000031
134       40   policy_sales_channel_32.0  0.000030
135       50   policy_sales_channel_42.0  0.000029
136       11    policy_sales_channel_2.0  0.000028
137       70   policy_sales_channel_62.0  0.000027
138      133  policy_sales_channel_128.0  0.000026
139       99   policy_sales_channel_94.0  0.000026
140       17    policy_sales_channel_9.0  0.000025
141      106  policy_sales_channel_101.0  0.000024
142      136  policy_sales_channel_131.0  0.000023
143       86   policy_sales_channel_80.0  0.000023
144      119  policy_sales_channel_114.0  0.000023
145      111  policy_sales_channel_106.0  0.000021
146       77   policy_sales_channel_69.0  0.000019
147       71   policy_sales_channel_63.0  0.000019
148      116  policy_sales_channel_111.0  0.000019
149      143  policy_sales_channel_138.0  0.000019
150       97   policy_sales_channel_92.0  0.000016
151       92   policy_sales_channel_87.0  0.000016
152       62   policy_sales_channel_54.0  0.000015
153       56   policy_sales_channel_48.0  0.000014
154       84   policy_sales_channel_78.0  0.000014
155      162  policy_sales_channel_159.0  0.000000
156      113  policy_sales_channel_108.0  0.000000
157      152  policy_sales_channel_149.0  0.000000
158       57   policy_sales_channel_49.0  0.000000
159       83   policy_sales_channel_76.0  0.000000
160       82   policy_sales_channel_75.0  0.000000
161       81   policy_sales_channel_74.0  0.000000
162       80   policy_sales_channel_73.0  0.000000
163       79   policy_sales_channel_71.0  0.000000
164       78   policy_sales_channel_70.0  0.000000
165       76   policy_sales_channel_68.0  0.000000
166       75   policy_sales_channel_67.0  0.000000
167       72   policy_sales_channel_64.0  0.000000
168       66   policy_sales_channel_58.0  0.000000
169       65   policy_sales_channel_57.0  0.000000
170       59   policy_sales_channel_51.0  0.000000
171       58   policy_sales_channel_50.0  0.000000
172       55   policy_sales_channel_47.0  0.000000
173      151  policy_sales_channel_148.0  0.000000
174       54   policy_sales_channel_46.0  0.000000
175       51   policy_sales_channel_43.0  0.000000
176       49   policy_sales_channel_41.0  0.000000
177       47   policy_sales_channel_39.0  0.000000
178       46   policy_sales_channel_38.0  0.000000
179       42   policy_sales_channel_34.0  0.000000
180       41   policy_sales_channel_33.0  0.000000
181       36   policy_sales_channel_28.0  0.000000
182       35   policy_sales_channel_27.0  0.000000
183       28   policy_sales_channel_20.0  0.000000
184       26   policy_sales_channel_18.0  0.000000
185       25   policy_sales_channel_17.0  0.000000
186       14    policy_sales_channel_6.0  0.000000
187       85   policy_sales_channel_79.0  0.000000
188       88   policy_sales_channel_82.0  0.000000
189       89   policy_sales_channel_83.0  0.000000
190       90   policy_sales_channel_84.0  0.000000
191      149  policy_sales_channel_146.0  0.000000
192      147  policy_sales_channel_144.0  0.000000
193      146  policy_sales_channel_143.0  0.000000
194      145  policy_sales_channel_140.0  0.000000
195      144  policy_sales_channel_139.0  0.000000
196      142  policy_sales_channel_137.0  0.000000
197      139  policy_sales_channel_134.0  0.000000
198      138  policy_sales_channel_133.0  0.000000
199      135  policy_sales_channel_130.0  0.000000
200      131  policy_sales_channel_126.0  0.000000
201      128  policy_sales_channel_123.0  0.000000
202      123  policy_sales_channel_118.0  0.000000
203      122  policy_sales_channel_117.0  0.000000
204      120  policy_sales_channel_115.0  0.000000
205      117  policy_sales_channel_112.0  0.000000
206      115  policy_sales_channel_110.0  0.000000
207      112  policy_sales_channel_107.0  0.000000
208      110  policy_sales_channel_105.0  0.000000
209      107  policy_sales_channel_102.0  0.000000
210      105  policy_sales_channel_100.0  0.000000
211      104   policy_sales_channel_99.0  0.000000
212      103   policy_sales_channel_98.0  0.000000
213      102   policy_sales_channel_97.0  0.000000
214      101   policy_sales_channel_96.0  0.000000
215      100   policy_sales_channel_95.0  0.000000
216       94   policy_sales_channel_89.0  0.000000
217       93   policy_sales_channel_88.0  0.000000
218      109  policy_sales_channel_104.0  0.000000

In [29]:
model.feature_importances_

array([1.86645065e-01, 6.24088933e-02, 4.61689104e-04, 2.13793109e-01,
       7.23414267e-03, 2.66025237e-02, 1.52246375e-01, 1.60644871e-01,
       3.61321038e-03, 1.77361030e-02, 2.36391463e-04, 2.83447718e-05,
       6.58256767e-04, 4.62063923e-04, 0.00000000e+00, 4.71099598e-04,
       6.36927923e-04, 2.49470237e-05, 2.18681035e-04, 4.76192373e-04,
       2.24295673e-04, 1.15894623e-03, 3.26260331e-04, 1.97697182e-04,
       2.47922262e-04, 0.00000000e+00, 0.00000000e+00, 1.50633890e-04,
       0.00000000e+00, 5.52713906e-05, 1.25998540e-04, 2.53275178e-04,
       5.04828228e-04, 1.26330251e-03, 4.06670988e-03, 0.00000000e+00,
       0.00000000e+00, 2.50368798e-04, 7.74011336e-04, 5.33153747e-04,
       3.03721024e-05, 0.00000000e+00, 0.00000000e+00, 3.99564814e-05,
       1.11998786e-04, 1.27588415e-04, 0.00000000e+00, 0.00000000e+00,
       3.38881746e-05, 0.00000000e+00, 2.90140307e-05, 0.00000000e+00,
       1.41384275e-04, 3.29874874e-05, 0.00000000e+00, 0.00000000e+00,
       1.44909678e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       6.35469130e-04, 3.16349618e-05, 1.47385640e-05, 9.26244512e-04,
       1.08465323e-04, 0.00000000e+00, 0.00000000e+00, 1.05152376e-04,
       1.52478597e-04, 2.47027923e-04, 2.68029752e-05, 1.92414456e-05,
       0.00000000e+00, 3.46697925e-05, 3.68602431e-05, 0.00000000e+00,
       0.00000000e+00, 1.92414456e-05, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.38896631e-05, 0.00000000e+00, 2.26654103e-05, 4.55676652e-05,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.26937250e-05,
       1.59035931e-05, 0.00000000e+00, 0.00000000e+00, 3.14221169e-05,
       1.42176510e-04, 1.62205005e-05, 4.06638134e-05, 2.60377014e-05,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 2.43246477e-05, 0.00000000e+00,
       3.10504453e-05, 0.00000000e+00, 0.00000000e+00, 2.07145743e-05,
       0.00000000e+00, 0.00000000e+00, 1.43857974e-04, 0.00000000e+00,
       1.92414456e-05, 0.00000000e+00, 6.36217187e-05, 2.26654103e-05,
       0.00000000e+00, 1.01442978e-04, 0.00000000e+00, 0.00000000e+00,
       4.04576867e-05, 2.79294887e-04, 4.87807153e-05, 3.66238355e-03,
       0.00000000e+00, 7.26163804e-03, 6.44120497e-04, 0.00000000e+00,
       4.25657561e-05, 2.64537025e-05, 3.62099475e-05, 0.00000000e+00,
       2.27761808e-05, 4.02455664e-05, 0.00000000e+00, 0.00000000e+00,
       3.31740883e-05, 1.59229841e-04, 0.00000000e+00, 1.92414456e-05,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.02267357e-04, 0.00000000e+00, 2.21499194e-04, 0.00000000e+00,
       0.00000000e+00, 2.91595484e-04, 5.11535436e-04, 3.47328897e-03,
       1.81989365e-04, 3.79010163e-03, 1.00460880e-03, 2.82304479e-03,
       3.61912056e-03, 5.29741471e-04, 0.00000000e+00, 3.68187019e-03,
       1.51878170e-03, 6.29878400e-04, 4.98162219e-04, 1.32381980e-03,
       3.35006423e-03, 1.23773305e-03, 8.82467183e-04, 1.85921516e-03,
       2.11802802e-03, 6.92628553e-03, 1.19344223e-03, 1.18046334e-03,
       3.22510555e-03, 1.62543860e-03, 1.35352951e-03, 1.93892301e-03,
       3.82642200e-03, 6.56355942e-04, 8.86551200e-04, 2.86751507e-03,
       1.19452551e-03, 1.16800609e-03, 1.30941323e-03, 5.41464680e-04,
       1.47819391e-03, 1.47579873e-03, 7.29660999e-04, 9.30033650e-04,
       1.16558211e-03, 9.76637236e-03, 3.54837983e-03, 2.76798630e-03,
       8.82254383e-04, 1.13230020e-03, 2.41927419e-03, 8.12867058e-04,
       2.84402845e-03, 2.39167136e-03, 1.71744076e-03, 1.64943969e-03,
       2.08792078e-03, 9.10799172e-04, 4.88621117e-03, 1.59697423e-04,
       1.07858621e-03, 2.39359075e-04, 2.83259704e-03, 5.29610741e-03,
       2.77879369e-03, 1.45590120e-03, 6.40521552e-04, 1.76371012e-03,
       2.03504361e-04, 1.73662579e-04, 1.54470878e-02])

# 4 - Treinamento dos modelos

In [30]:
# trbalhar com as colunas abaixo
# Age, 
# Vehichle_Age
# Annual Premium 
# vintage, 
# Response